<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{{ $report->name }}</title>
<style>
  body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #333; }
  h1 { font-size: 20px; color: #1a56db; margin-bottom: 4px; }
  .subtitle { color: #666; font-size: 11px; margin-bottom: 20px; }
  table { width: 100%; border-collapse: collapse; margin-top: 16px; }
  th, td { padding: 8px 10px; text-align: left; border-bottom: 1px solid #e5e7eb; }
  th { background: #f3f4f6; font-weight: 600; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; }
  .footer { margin-top: 24px; padding-top: 12px; border-top: 1px solid #e5e7eb; font-size: 10px; color: #9ca3af; }
  .meta { margin-bottom: 20px; }
  .meta dt { font-weight: 600; display: inline; }
  .meta dd { display: inline; margin-right: 24px; }
</style>
</head>
<body>
  <h1>{{ $report->name }}</h1>
  <p class="subtitle">{{ $report->description ?? '' }}</p>

  <dl class="meta">
    <dt>Generated:</dt> <dd>{{ $generated_at }}</dd>
    <dt>By:</dt> <dd>{{ $generated_by }}</dd>
    @if(!empty($params['start_date']))
      <dt>From:</dt> <dd>{{ $params['start_date'] }}</dd>
    @endif
    @if(!empty($params['end_date']))
      <dt>To:</dt> <dd>{{ $params['end_date'] }}</dd>
    @endif
    @if(!empty($params['branch_id']))
      <dt>Branch ID:</dt> <dd>{{ $params['branch_id'] }}</dd>
    @endif
  </dl>

  <p>This report was generated by the Reports Module. Detailed data can be accessed through the respective module pages.</p>

  <div class="footer">
    RFI Management Suite &mdash; {{ $report->category->name ?? 'Reports' }} &mdash; Confidential
  </div>
</body>
</html>
